### ISSUE TITLE
Value error while implementing the spacy_dbpedia_spotlight.load('en',nlp)

### ISSUE THREAD

**Issue by sairam9694** [MartinoMensio/spacy-dbpedia-spotlight#1]
for this script :
nlp = spacy.load('en_core_web_lg')
spacy_dbpedia_spotlight.load('en',nlp)
doc = nlp('The president of USA is calling Boris Johnson to decide what to do about coronavirus')
print("Entities", [(ent.text, ent.label_, ent.kb_id_) for ent in doc.ents])

output :-1: 
ValueError: [E103] Trying to set conflicting doc.ents: '(3, 4, 'ORG')' and '(3, 4, 'DBPEDIA_ENT')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.

**Comment by MartinoMensio** [comment]
Hi @sairam9694,
Thank you for submitting your issue. I updated the code to spaCy v3 and fixed this issue. See in the documentation the usage of the `overwrite_ents` configuration option.

Please let me know if this works for you.
Martino
