### ISSUE TITLE
400 Client Error for local model

### ISSUE THREAD

**Issue by Kittyuzu1207** [MartinoMensio/spacy-dbpedia-spotlight#20]
Hi! Thanks for your great contributions!
When I deployed the model locally and used it in this way:
`db_nlp = spacy.blank('en')  
db_nlp.add_pipe('dbpedia_spotlight', config={'dbpedia_rest_endpoint': 'http://localhost:2222/rest', 'confidence':0.35})`
I still met an error which mentioned below when I request frequently:
`2022-10-20 07:32:23.194 | WARNING  | spacy_dbpedia_spotlight.entity_linker:get_remote_response:239 - Bad response from server, probably too many requests. Consider using your own endpoint. Document not updated.
                400 Client Error: Bad Request for url: http://localhost:2222/rest/annotate`

Is it normal, or did I get anything wrong? Look forward to your help~

**Comment by acxcv** [comment]
Hi, I was facing the same problem. I don't know how to fix it and I didn't have enough capacity to dig deeper, but on a medium-sized dataset (36k texts) I was able to work around it using a monkey patch

```
# nlp is the spacy object as described in the examples
def nlp_wrapper(text):
        try:
            return nlp(text)
        except Exception as e:
            print(e)
            try:
                except_nlp = spacy.blank('en')
                except_nlp.add_pipe(
                    'dbpedia_spotlight', config={'confidence': confidence,
            })
                return except_nlp(text)
            except:
                return '[[ERROR]]'
```

With this snippet, my script processed as many texts as possible on the local server and fell back to the standard configuration using the web API. 
In case the call to the web API returned an error, too, it returned an error token that let me process the texts that produced an error later on in a second iteration.

On a side note:
I noticed that the behavior of the nlp object changes depending on the value for `'process'` in the config (`nlp._pipe_configs['dbpedia_spotlight']`) . In my case, with `'annotate'` it failed after processing ca. 9500 text whereas with `'candidates'`, it failed after ca. 1500 texts.

**Comment by MartinoMensio** [comment]
Hi @acxcv and @Kittyuzu1207 ,
Thank you for reporting this behaviour! 
Can you manage to capture one document which makes the local server fail and instead still works with the remote API?
I would like to reproduce it and analyse what goes wrong, so if you could provide this example, I can look into it.

Given that you already have the looping and the way to handle the error, you could add some lines to capture these specific documents.

I suspect this may be an encoding error or some character that makes something break, while on the remote API maybe they have some way to clean/escape the text.

Thank you again!

Martino

**Comment by acxcv** [comment]
Hi Martino, this is where it gets weird. 

The texts in question produce an error in the loop but don't do so when processing them outside the loop. Also, some texts that don't produce an error with `'config': 'annotate'` do so with `'config': 'candidates'`.

The dataset I'm working with is a private one. Let me verify if I can share it and I'll get back to you.

**Comment by MartinoMensio** [comment]
Hi @acxcv ,
Oh, then maybe there is an issue with firing too many requests in a short time. Could you check the logs from the local server? What if, on exception triggered, you wait for 1 second and retry with the same document?
Just to understand better the type of problem.

Martino

**Comment by MartinoMensio** [comment]
Hi @acxcv ,
I tried yesterday on your collection that you shared, and unfortunately I could not reproduce the issue.

Now I tried with your example and no exception is happening. I am wondering what the cause may be.

I see that you are working with dbpedia jar 1.0, while I am currently running dbpedia jar 1.1. Could you try with the new version and let me know if the situation is the same?

(From README.md)
```bash
# download main jar
wget https://repo1.maven.org/maven2/org/dbpedia/spotlight/rest/1.1/rest-1.1-jar-with-dependencies.jar
# download latest model (last checked on 10/10/2022) (assuming en model)
wget -O en.tar.gz http://downloads.dbpedia.org/repo/dbpedia/spotlight/spotlight-model/2022.03.01/spotlight-model_lang=en.tar.gz
# extract model
tar xzf en.tar.gz
# run server
java -Xmx8G -jar rest-1.1-jar-with-dependencies.jar en http://localhost:2222/rest
```

Martino

**Comment by acxcv** [comment]
Worked flawlessly with dbpedia jar 1.1. Thank you!

**Comment by MartinoMensio** [comment]
That's a very good news!

@Kittyuzu1207 could you try to see if the upgrade solves the issue also for you?

Martino

**Comment by Kittyuzu1207** [comment]
> 

Yes! The problem has been solved. Thank you for your efforts!
